name: Sync with upstream

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - name: Fetch release version
        run: |
          VERSION=$(
            curl -sL https://api.github.com/repos/xournalpp/xournalpp/tags | 
            jq .  | grep name | grep -v beta | grep -v rc | head -n 1 | cut -d'"' -f4
          )
          if [ ${#VERSION} -gt 0 ]; then
            sed -i '/^parts:/,/^[^ ]/ { /^  xournalpp:$/,/source-tag:/ s/^\( *source-tag: \).*/\1'"$VERSION"'/ }' snapcraft.yaml
          fi
          
      - name: Check for modified files
        id: git-check
        run: |
          MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
          echo "modified=$MODIFIED" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Roland Lötscher'
          git config --global user.email 'roland_loetscher@hotmail.com'
          git commit -am "Automatic sync to latest release"
          git push
